# Generated by Django 3.1.7 on 2021-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAuth', '0002_auto_20210406_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
