# Generated by Django 3.1.4 on 2020-12-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMpgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpg_file', models.FileField(upload_to='')),
                ('mpg', models.FloatField()),
                ('cylinders', models.IntegerField()),
                ('displacement', models.FloatField()),
                ('horsepower', models.FloatField()),
                ('weight', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('model_year', models.IntegerField()),
                ('origin', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
