# Generated by Django 3.1.4 on 2020-12-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autompgdata',
            name='mpg_file',
        ),
        migrations.RemoveField(
            model_name='autompgdata',
            name='user',
        ),
        migrations.CreateModel(
            name='AutoMpgFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpg_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
