# Generated by Django 3.1.4 on 2020-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20201228_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autompgfile',
            name='mpg_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
