# Generated by Django 3.1.4 on 2020-12-28 15:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20201228_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autompgfile',
            name='mpg_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/data_files'), upload_to=''),
        ),
    ]
