# Generated by Django 3.1.4 on 2020-12-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20201228_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autompgfile',
            name='mpg_file',
            field=models.FileField(upload_to='data_files/'),
        ),
    ]
