# Generated by Django 3.1.4 on 2020-12-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20201228_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='autompgdata',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.autompgfile'),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='cylinders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='displacement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='horsepower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='mpg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='origin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgdata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autompgfile',
            name='mpg_file',
            field=models.FileField(blank=True, null=True, upload_to='data_files/'),
        ),
    ]
